### ISSUE TITLE
'successors’ was not declared in this scope

### ISSUE THREAD

**Issue by bvanheu** [zneak/fcd#1]
I'm not able to compile `fcd` on Linux, i have the following error:

```
ast_backend.cpp:346:52: error: ‘successors’ was not declared in this scope
     for (auto succ : successors(current->getEntry()))
```

I'm using the following line:
```
g++ -std=c++11 -fpermissive  -c ast_backend.cpp
```

**Comment by zneak** [comment]
Are you using the prescribed LLVM version?

Try adding `#include <llvm/IR/CFG.h>`, that's where it should be declared.

**Comment by bvanheu** [comment]
I'm using the latest LLVM version, 3.6.2. What version should I be using?

**Comment by zneak** [comment]
fcd uses dberlin's [llvm-gvn-rewrite](https://github.com/dberlin/llvm-gvn-rewrite), which includes the `MemorySSA` utility (not yet found in mainstream).

Also, I haven't updated since May 20th because that's a notoriously hard thing to do and I had approaching deadlines, so I can't guarantee that it'll build with anything more recent than revision e7a8826a52bba231c7e60323a991b00deab915b2. I plan to look into that next week.

**Comment by bvanheu** [comment]
great thanks, it didn't get that Daniel Berlin was the version of LLVM I needed to build your stuff, i thought you only took part of his project to make `fcd`.
