### ISSUE TITLE
Possible SEGFAULT in anyarch calling convention

### ISSUE THREAD

**Issue by Lukas-Dresel** [zneak/fcd#21]
In Line 405 of callconv/anyarch_anycc.cpp callInfo.getStage() is called without checking if callInfo is nullptr. This can result in a Null-pointer dereference if analysis failed according to comments in callconv/params_registry.cpp

If you tell me what you want the error handling in this case to do i can fix it. When looking at the rest of that function intuitively i would simply add an assertion as is done for the registerInfo in Line 382,
which according to targetinfo.cpp can also be a nullptr if the architecture is not x86.

**Comment by zneak** [comment]
Currently, we can't get to a point where `TargetInfo` is relevant if the architecture isn't x86 as we won't even do IR generation. In fact, `largestOverlappingRegister` should probably return a reference and call `llvm_unreachable` if it couldn't find the register. This can really only fail if we passed a `TargetRegisterInfo` instance that does not belong to that `TargetInfo`.

A catch-all parameter identification mechanism is extremely tricky to get right and I can't claim that fcd has it right. This piece of code would need a lot of love to be truly useful.

The strictly correct thing to do here would be to abort analysis since we can't know for sure that we'll get the parameters right (the call could pass through parameters that the caller otherwise doesn't reference). However, it might be more helpful to just ignore that case when it comes up. It may cause inaccurate results but wouldn't cause every function in the graph to fail parameter identification.

In that case, it might be better not to grab a reference and just test that the result is not `nullptr`. Either way, I think that adding an assert doesn't solve the problem.

**Comment by Lukas-Dresel** [comment]
But i did somehow manage to reach that case. The problem is that i don't exactly remember how. I was messing around with having an input llvm file and running passes individually and then it crashed.
Is llvm_unreachable what causes the llvm.trap() IR statements?

**Comment by zneak** [comment]
Are you talking about `largestOverlappingRegister`? If so, that's a bug with it. It's supposed to find the largest register that contains a smaller one (for instance, map `al` to `rax`).

The `llvm.map` statements are generated for the `hlt` instruction (see [Lifting x86 code into LLVM bitcode](http://zneak.github.io/fcd/2016/02/16/lifting-x86-code.html) and then [the implementation of hlt](https://github.com/zneak/fcd/blob/master/fcd/cpu/x86.emulator.cpp#L764) if you're curious). It's possible that some other built-in LLVM pass adds some, but that's the primary cause.

`llvm_unreachable` isn't related to codegen. It's a `noreturn` function that aborts execution.

**Comment by zneak** [comment]
I made `largestOverlappingRegister` return a reference (be sure to file a bug report if you ever hit the `llvm_unreachable`!) and made anyarch_anycc forgive unavailable CallInfos.

Thanks for bringing this up and diving in the source 👍

**Comment by Lukas-Dresel** [comment]
Then i'll close this issue and reopen it if any problems pop up again. Thanks!
