### ISSUE TITLE
Questions about passes in fcd

### ISSUE THREAD

**Issue by Lukas-Dresel** [zneak/fcd#26]
Are the intermediate instructions referencing undefined values that are introduced by the sroa pass runs intended? Since SROA is a LLVM pass what makes this happen?

E.g. https://github.com/Lukas-Dresel/fcd/blob/pipelinetesting/pipeline/testing/005_post_sroa.ll#L363

**Comment by Lukas-Dresel** [comment]
Currently incorrect question, based on erroneous script, will fix and reopen once correct.

**Comment by Lukas-Dresel** [comment]
Adjusted for wrong debug_pipeline.py script, now correct passes are given.

**Comment by Lukas-Dresel** [comment]
Before: https://github.com/Lukas-Dresel/fcd/blob/pipelinetesting/pipeline/testing/004_post_modulethinner.ll#L646-L698
##########################################################################
After: https://github.com/Lukas-Dresel/fcd/blob/pipelinetesting/pipeline/testing/005_post_sroa.ll#L357-L372

**Comment by zneak** [comment]
This happens because the argument recovery process removes the register structure pointer passed as a parameter and puts it on the stack, and then SROA then correctly identifies that we read from the field at index 21 (the `fs` register) without writing to it beforehand, and folds it into an `undef` constant.

The most relevant use of `fs` that I've seen in Linux program is to load stack cookies. I'm not actually sure what `fs` is meant to point to on Linux (I know that it's TLS on Windows but I've never bothered to check on Linux).

Since segment selectors are special and rarely changed, I wouldn't consider it right to include them in argument recovery. One solution could be to make the segment registers special globals instead of including them in the register structure.

**Comment by Lukas-Dresel** [comment]
As far as i know this depends on whether its 32 or 64 bit Linux. One of them is for thread-local-storage, the other for processor-specific storage, but i'm not sure which is which.

**Comment by Lukas-Dresel** [comment]
On the other hand, would it be bad to consider them arguments? syntactically i think this would make a lot of sense, since it immediately gives information about whether or not a function uses TLS, exception handling (at least on windows), or stack cookies or the likes.

What are the downsides to treating them as function arguments?

**Comment by zneak** [comment]
If a function in a call graph accepts segment selectors as parameters, then every function on a path that may lead to it must also accept fs even if for nothing else than passing it to the next function.
