### ISSUE TITLE
Trailing whitespace characters in the empty strings

### ISSUE THREAD

**Issue by XVilka** [zneak/fcd#50]
Seems that your Xcode (similar to files created in Visual Studio) creates a lot of whitespace on pressing Enter or something like that...). You can check this project https://github.com/google/google-toolbox-for-mac

**Comment by zneak** [comment]
I haven't turned on trimming of whitespace-only lines. It's not a conscious decision, but I don't perceive it as being an issue of significance. The whitespace could change in the future, but for now I don't care about it.

**Comment by zneak** [comment]
I use issues to track things that I know have to happen at some point. I closed this because I don't think that it has a significant impact on the developer experience and it has no impact on the final product. It could still be resolved in the future, I just don't think that it's important to track it.
