### ISSUE TITLE
LLVMBuildLandingPad signature changed

### ISSUE THREAD

**Issue by rk700** [zneak/fcd#6]
Hi,

I'm using clang 3.7.1 but the compilation failed, which says that `LLVMBuildLandingPad`(https://github.com/zneak/fcd/blob/master/fcd/python/bindings.cpp#L2091) requires 5 arguments while 4 provided. Then I searched and found that the signature of this function has been changed:
http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/lang/clang/Makefile.common?rev=1.11&content-type=text/x-cvsweb-markup

It seems that the function would need 4 arguments only in clang 3.7.0, and I'm wondering if it would be better to change the code accordingly.

Thanks.

**Comment by zneak** [comment]
Yes, I saw that in the [release notes](http://llvm.org/releases/3.7.1/docs/ReleaseNotes.html#major-changes-in-3-7-1).

LLVM tends to break API compatibility **a lot**, and that's the main reason I stick to tagged releases for development. As it happens, *usually*, minor releases don't break API compatibility, but this one does. I'm not interested in supporting multiple versions of LLVM, so when the build document says 3.7, it means 3.7.

That said, the file that broke is a tool-generated file that I included in source control because I didn't bother to have the build system make it automatically. I want to change that eventually, hopefully in a near future. That would solve this specific compatibility problem, but I don't really want to guarantee any kind of compatibility with versions other than the one that I specifically target.

As LLVM 3.8 will come out in a matter of days and I plan to upgrade, there's no point in upgrading to LLVM 3.7.1 now. If you have 3.7.1 and don't want to have a side-by-side install of 3.7, you should probably just comment the offending line. Fcd doesn't use landing pads anyway, so you won't miss out on anything.
